### ISSUE TITLE
Project Plan submitted.

### ISSUE THREAD

**Issue by spartan7777** [spartan7777/Individual-Enterprise-Project#4]
Here is the plan I am using to try to accomplish the completion of this project. Hopefully this will help explain my train of thought,  my problem solving methodology and why some of the other documentation was created.

**Comment by pawaitemadisoncollege** [comment]
@spartan7777 It looks like you have a good idea of the big pieces of work that need to be completed!

- [ ] It would be helpful to have an indicator in this plan as to when an item is complete.
- [ ] With regard to this item, https://github.com/spartan7777/Individual-Enterprise-Project/blob/b51e0118f76d102fe8ea81b36d24ccdab195b79a/ProjectPlan/EnterpriseJava_Fall2020_Ogedengbe_ConceptCompendium_ProjectPlan.txt#L21-L23. there not be much logic/code in the jsps. Remember that while php programs include logic and database access mixed right in with the html, in java-land, the jsps just provide a view of the data;  the logic to get the data will exist in the controller, entity and dao. As part of this step in your plan, it might be helpful to indicate what controller/s and entities  will be used to produce the data for each jsp. Entities are 1:1 with tables.  If you have a User table, you will have a User entity.
- [ ] Just a clarification: https://github.com/spartan7777/Individual-Enterprise-Project/blob/b51e0118f76d102fe8ea81b36d24ccdab195b79a/ProjectPlan/EnterpriseJava_Fall2020_Ogedengbe_ConceptCompendium_ProjectPlan.txt#L37 There should not be any java code in the jsps - java code will go in java classes.  Your jsps will have html, expression language and jstl for display.
